### ISSUE TITLE
ODM Content Category is not working properly

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_theme#313]
There are many news are categorized under a category, if the unset the limited number, it shows a lot, but the limited number (5-10) are set it show only one or a few. 

Suggestion: update the query to filter posts by category with the limited number instead of query all with array_intersect.

**Comment by Huyeng** [comment]
If the  max number of posts to list is 5 or 10: it lists only one.
![screenshot_4](https://cloud.githubusercontent.com/assets/6613530/17966694/080ed330-6aed-11e6-9c7a-5ce340f9160c.png)


- If the  max number of posts to list is -1: 
![screenshot_3](https://cloud.githubusercontent.com/assets/6613530/17966647/ccdaaf82-6aec-11e6-9094-d29c6a8fccd0.png)

**Comment by acorbi** [comment]
@Huyeng You assigned yourslef this task... are you going to work on it or should I?

**Comment by Huyeng** [comment]
I will do it because you have to work on wpckan to filter the  datasets from CKSN that have the same category of the post.

**Comment by acorbi** [comment]
@Huyeng the issue with the filter of the datasets with same category of the post should be fixed: https://github.com/OpenDevelopmentMekong/wpckan/commit/ce61976bcb78ce787183ea31fd1ecea2f0987028

**Comment by acorbi** [comment]
@Huyeng the issue with the filter of the datasets with same category of the post should be fixed: https://github.com/OpenDevelopmentMekong/wpckan/commit/ce61976bcb78ce787183ea31fd1ecea2f0987028

**Comment by acorbi** [comment]
@Huyeng you fixed this issue already right? please close this issue if that is the case

**Comment by Huyeng** [comment]
The updated code works for my local environment, but on the PP, don't why even the code was pulled. Technically it should work.  On the Access to public service page, the number of related news and announcement just was set up to 100 or 500, but there are about about 5 of each post type are shown.

**Comment by acorbi** [comment]
@Huyeng that could be the expected behaviour, couldn't it? The limit value is the maximum but the widget will show less entries if there are not many related resources. I am going to close this issue, we should re-open if the problem happens again

**Comment by Huyeng** [comment]
No, the issue has still existed. 
The limit value is the maximum but the widget will show less entries if there are not many related resources. (in this case is correct).  However, there are many posts of that category, but the related posts shown less then limited number. 

For example, there are many news posts in Government Services: https://cambodia.opendevelopmentmekong.net/category/government/government-services?queried_post_type=news-article

In the widget, the max-number is set 5, so the five posts for the links above should list in the related widget of the access to public service page, but in face, there are only two posts listed. 
https://cambodia.opendevelopmentmekong.net/profiles/access-to-public-service/
